name: Check external links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check links in guides and documentation
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --max-retries 2
            --timeout 20
            './**/*.html'
            './**/*.md'
          fail: true
